[project]
name = "weather-road-safety"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.14"
dependencies = [
    "google-cloud-bigquery>=3.45.2",
    "google-cloud-storage>=3.14.1",
    "pandas>=3.0.6",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
]

[project.scripts]
weather-road-safety = "weather_road_safety:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
